name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -o dist/trxsh cmd/main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: trxsh
          path: dist/trxsh
